from banglaword import BanglaWord

object = BanglaWord()
print(object.bangla_number(1500.50))
print(object.bangla_word(9))
print(object.bangla_word(90.9))
print(object.bangla_word_in_format(900))
print(object.bangla_word_in_format(9999))
print(object.bangla_word_in_format(9999.09))
print(object.bangla_word_in_format(82))
print(object.bangla_word_in_format(1895652))
print(object.bangla_month(1))
print(object.bangla_month(2))
print(object.bangla_month(3))
print(object.bangla_month(4))
print(object.bangla_month(5))
print(object.bangla_month(6))
print(object.bangla_month(7))
print(object.bangla_month(8))
print(object.bangla_month(9))
print(object.bangla_month(10))
print(object.bangla_month(11))
print(object.bangla_month(12))
print(object.bangla_day(1))
print(object.bangla_day(2))
print(object.bangla_day(3))
print(object.bangla_day(4))
print(object.bangla_day(5))
print(object.bangla_day(6))
print(object.bangla_day(7))
print(object.bangla_word_in_format(9999.99009))
# print(object.bangla_word_in_format(82))
# print(object.bangla_word_in_format(1895652))
# print(object.moeny_format(0.00))
